Repository mantidproject/mslice, pull requests merged in 2018-03, with the labels that each got.

#266 Fix error when cancelling interactive cut
  mslice/models/cut/matplotlib_cut_plotter.py
  mslice/plotting/plot_window/plot_figure.py
Labels: bug

#267 Fix MDHistoWorkspace errors
  mslice/models/workspacemanager/mantid_workspace_provider.py
  mslice/plotting/plot_window/interactive_cut.py
Labels: bug

#268 Fix save error
  mslice/models/workspacemanager/file_io.py
Labels: bug

#274 Fix ylim not setting correctly
  mslice/models/cut/cut_plotter.py
  mslice/models/cut/matplotlib_cut_plotter.py
  mslice/presenters/cut_presenter.py
Labels: bug

#275 Dataloader usability fixes
  mslice/widgets/dataloader/dataloader.py
Labels: enhancement

#269 Select and update loaded workspaces
  mslice/presenters/data_loader_presenter.py
  mslice/presenters/main_presenter.py
  mslice/tests/data_loader_test.py
Labels: bug

#280 Pre-beta release bug fixes and improvements
  mslice/models/cut/matplotlib_cut_plotter.py
  mslice/models/workspacemanager/mantid_workspace_provider.py
  mslice/plotting/plot_window/plot_figure.py
  mslice/presenters/data_loader_presenter.py
  mslice/tests/data_loader_test.py
  mslice/util/qt/QtGui.py
  mslice/util/qt/QtWidgets.py
  mslice/widgets/dataloader/dataloader.py
  mslice/widgets/dataloader/inputdialog.py
Labels: High priority, bug, enhancement

#278 Interactive cuts fixes
  mslice/models/cut/matplotlib_cut_plotter.py
  mslice/models/slice/mantid_slice_algorithm.py
  mslice/models/workspacemanager/mantid_workspace_provider.py
  mslice/plotting/plot_window/cut_plot.py
  mslice/plotting/plot_window/interactive_cut.py
  mslice/plotting/plot_window/plot_figure.py
  mslice/plotting/plot_window/plot_window.ui
  mslice/plotting/plot_window/slice_plot.py
Labels: High priority, bug, enhancement

#286 Fix intensity off-by-one broadcasting error
  mslice/models/alg_workspace_ops.py
Labels: bug

#287 Fix cut window missing plot_handler
  mslice/models/cut/matplotlib_cut_plotter.py
  mslice/plotting/plot_window/plot_figure.py
Labels: bug

#288 Move overplot members to PlotFigureManager
  mslice/plotting/plot_window/plot_figure.py
  mslice/plotting/plot_window/slice_plot.py
Labels: bug

#292 Move check_mpl call
  .travis.yml
  mslice/app/__init__.py
  mslice/models/cut/matplotlib_cut_plotter.py
  mslice/models/slice/matplotlib_slice_plotter.py
  mslice/plotting/pyplot.py
  mslice/util/__init__.py
Labels: bug

#299 Updated docs for beta release
  docs/source/conf.py
  docs/source/cutting.rst
  docs/source/images/cutting/cut_options.png
  docs/source/images/cutting/cut_panel.png
  docs/source/images/cutting/cut_tab_show_params.png
  docs/source/images/cutting/cuts_saved_to_workspace.png
  docs/source/images/cutting/mandatory_values.png
  docs/source/images/cutting/multiple_cuts_in_one_window.png
  docs/source/images/cutting/single_cut.png
  docs/source/images/cutting/width_cuts.png
  docs/source/images/cutting/width_parameters_set.png
  docs/source/images/quickstart/calc_proj.png
  docs/source/images/quickstart/cut_plotted.png
  docs/source/images/quickstart/cut_q.png
  docs/source/images/quickstart/data_tab.png
  docs/source/images/quickstart/interactive_cuts.png
  docs/source/images/quickstart/keep.png
  docs/source/images/quickstart/load_tab.png
  docs/source/images/quickstart/mantid_interfaces_menu.png
  docs/source/images/quickstart/multi_cut.png
  docs/source/images/quickstart/projection_calculated.png
  docs/source/images/quickstart/slice_intensity.png
  docs/source/images/quickstart/slice_parameters.png
  docs/source/images/quickstart/slice_plotted.png
  docs/source/images/quickstart/started_mslice.png
  docs/source/images/quickstart/subtract_dialog.png
  docs/source/images/quickstart/subtract_slice.png
  docs/source/images/quickstart/workspace_loaded.png
  docs/source/images/slicing/calculate_projection.png
  docs/source/images/slicing/intensity_chi.png
  docs/source/images/slicing/powder_lines.png
  docs/source/images/slicing/recoil.png
  docs/source/images/slicing/slice_options.png
  docs/source/images/slicing/slice_parameters.png
  docs/source/index.rst
  docs/source/quickstart.rst
  docs/source/slicing.rst
Labels: enhancement

#300 Remembering cut axes in non-PSD mode
  mslice/app/mainwindow.py
  mslice/models/cut/cut_plotter.py
  mslice/presenters/cut_presenter.py
  mslice/presenters/slice_plotter_presenter.py
  mslice/presenters/workspace_manager_presenter.py
  mslice/tests/cut_presenter_test.py
  mslice/tests/slice_plotter_presenter_test.py
  mslice/views/cut_view.py
  mslice/views/slice_plotter_view.py
  mslice/views/workspace_view.py
  mslice/widgets/cut/cut.py
  mslice/widgets/workspacemanager/__init__.py
  mslice/widgets/workspacemanager/command.py
  mslice/widgets/workspacemanager/workspacemanager.py
Labels: bug
