Repository mantidproject/mslice, pull requests merged in 2018-07, with the labels that each got.

#345 Normalisation to unity
  mslice/models/cut/cut.py
  mslice/models/cut/cut_normalisation.py
  mslice/models/slice/slice_functions.py
Labels: High priority, bug

#349 E_fixed propagation
  mslice/models/workspacemanager/workspace_algorithms.py
Labels: bug

#351 Tidy up SlicePlotterPresenter validation methods
  mslice/presenters/slice_plotter_presenter.py
  mslice/widgets/slice/slice.py
Labels: technical debt

#354 CLI - Fix workspace type error in MakeProjection
  mslice/models/cut/cut_functions.py
  mslice/models/projection/powder/make_projection.py
  mslice/models/projection/powder/mantid_projection_calculator.py
  mslice/models/slice/slice_functions.py
  mslice/models/workspacemanager/workspace_algorithms.py
  mslice/presenters/slice_plotter_presenter.py
  mslice/tests/slice_functions_test.py
Labels: bug
