Repository mantidproject/mslice, pull requests merged in 2019-03, with the labels that each got.

#444 Cut plotter bugsfixes
  mslice/cli/helperfunctions.py
  mslice/plotting/plot_window/cut_plot.py
  mslice/plotting/plot_window/interactive_cut.py
  mslice/presenters/cut_plotter_presenter.py
  mslice/scripting/__init__.py
  mslice/scripting/helperfunctions.py
  mslice/tests/command_line_test.py
  mslice/tests/cut_plotter_presenter_test.py
Labels: High priority, bug

#441 Add tests for script generation and CLI functions
  mslice/cli/_mslice_commands.py
  mslice/cli/helperfunctions.py
  mslice/plotting/plot_window/cut_plot.py
  mslice/presenters/cut_plotter_presenter.py
  mslice/scripting/__init__.py
  mslice/scripting/helperfunctions.py
  mslice/tests/cli_helper_functions_test.py
  mslice/tests/cli_mslice_projection_test.py
  mslice/tests/command_line_test.py
  mslice/tests/cut_plot_test.py
  mslice/tests/scripting_helperfunctions_test.py
  mslice/tests/scripting_tests.py
  mslice/tests/slice_plot_test.py
Labels: review wanted

#449 Update the update_legend function in slice_plot.py
  mslice/plotting/plot_window/slice_plot.py
  mslice/tests/slice_plot_test.py
Labels: review wanted

#450 Minor bugs fixes
  mslice/cli/_mslice_commands.py
  mslice/models/workspacemanager/file_io.py
  mslice/plotting/globalfiguremanager.py
  mslice/plotting/plot_window/cut_plot.py
  mslice/plotting/plot_window/interactive_cut.py
  mslice/plotting/plot_window/plot_figure_manager.py
  mslice/plotting/plot_window/slice_plot.py
  mslice/presenters/cut_plotter_presenter.py
  mslice/presenters/workspace_manager_presenter.py
  mslice/tests/command_line_test.py
  mslice/tests/file_io_test.py
  mslice/tests/slice_functions_test.py
Labels: High priority, bug

#456 Add image copy button to plots
  mslice/plotting/plot_window/plot_figure_manager.py
  mslice/plotting/plot_window/plot_window.py
Labels: enhancement

#455 Fix 2theta units naming bug
  mslice/models/cut/cut_algorithm.py
  mslice/models/labels.py
  mslice/models/slice/slice_functions.py
  mslice/presenters/slice_plotter_presenter.py
Labels: bug

#453 Fixed bug to allow plotting indirect nxspe files
  mslice/models/cut/cut_algorithm.py
  mslice/models/slice/slice_algorithm.py
  mslice/models/slice/slice_functions.py
  mslice/models/workspacemanager/workspace_algorithms.py
  mslice/presenters/data_loader_presenter.py
  mslice/tests/data_loader_test.py
Labels: bug
