Repository mantidproject/mslice, pull requests merged in 2019-07, with the labels that each got.

#471 Subtract script generation bugfix
  buildscripts/buildscript.sh
  mslice/cli/_mslice_commands.py
  mslice/models/cut/cut_algorithm.py
  mslice/models/workspacemanager/workspace_algorithms.py
  mslice/scripting/__init__.py
  mslice/scripting/helperfunctions.py
  mslice/tests/scripting_helperfunctions_test.py
  mslice/tests/scripting_tests.py
  mslice/tests/workspace_provider_test.py
  mslice/util/mantid/algorithm_wrapper.py
Labels: bug

#476 SaveToADS button now enabled in workbench
  mslice/app/__init__.py
  mslice/app/mainwindow.py
  mslice/util/mantid/__init__.py
Labels: bug

#479 Fix flake8 complexity warnings
  mslice/presenters/workspace_manager_presenter.py
  mslice/scripting/__init__.py
Labels: maintenance

#484 Disabled Save Cut to Workspace until area selected
  mslice/plotting/plot_window/interactive_cut.py
  mslice/plotting/plot_window/slice_plot.py
Labels: bug

#486 Pop up error dialog on invalid LaTeX string
  mslice/plotting/plot_window/cut_plot.py
  mslice/plotting/plot_window/plot_figure_manager.py
  mslice/plotting/plot_window/quick_options.py
  mslice/plotting/plot_window/slice_plot.py
  mslice/presenters/quick_options_presenter.py
  mslice/tests/quick_options_test.py
Labels: bug

#477 Fix cut saving bugs
  mslice/models/workspacemanager/file_io.py
  mslice/models/workspacemanager/workspace_algorithms.py
  mslice/plotting/plot_window/cut_plot.py
  mslice/plotting/plot_window/plot_figure_manager.py
  mslice/views/cut_plotter.py
Labels: bug

#470 Add SaveAscii to _mslice_commands
  mslice/cli/_mslice_commands.py
  mslice/cli/helperfunctions.py
  mslice/workspace/workspace.py
Labels: review wanted

#488 Restrict slices to always have DeltaE as an axis
  mslice/widgets/slice/slice.py
Labels: bug

#489 Fixed errors in documentation
  docs/source/cli.rst
Labels: bug

#487 Workspace manager unit tests
  mslice/presenters/workspace_manager_presenter.py
  mslice/tests/workspacemanager_presenter_test.py
  mslice/util/mantid/algorithm_wrapper.py
Labels: maintenance

#494 Fix is_cut check
  mslice/cli/helperfunctions.py
Labels: High priority, bug

#491 Integration option for cuts
  mslice/app/mainwindow.py
  mslice/app/mainwindow.ui
  mslice/cli/_mslice_commands.py
  mslice/cli/plotfunctions.py
  mslice/models/cut/cut.py
  mslice/models/cut/cut_algorithm.py
  mslice/models/cut/cut_functions.py
  mslice/presenters/cut_plotter_presenter.py
  mslice/presenters/cut_widget_presenter.py
  mslice/presenters/interfaces/main_presenter.py
  mslice/presenters/main_presenter.py
  mslice/scripting/__init__.py
  mslice/scripting/helperfunctions.py
  mslice/tests/cut_widget_presenter_test.py
  mslice/views/interfaces/mainview.py
  mslice/workspace/histogram_workspace.py
Labels: enhancement

#495 Keep dialog open
  mslice/plotting/plot_window/cut_plot.py
  mslice/plotting/plot_window/plot_options.py
  mslice/plotting/plot_window/plot_options.ui
  mslice/plotting/plot_window/plot_window.py
  mslice/plotting/plot_window/quick_options.py
  mslice/plotting/plot_window/slice_plot.py
  mslice/presenters/plot_options_presenter.py
  mslice/presenters/quick_options_presenter.py
  mslice/tests/quick_options_test.py
Labels: enhancement

#501 Added menu option to save script to clipboard
  mslice/plotting/plot_window/cut_plot.py
  mslice/plotting/plot_window/plot_window.py
  mslice/plotting/plot_window/slice_plot.py
  mslice/scripting/__init__.py
Labels: enhancement

#500 Fixed ads export bug
  mslice/models/cut/cut_algorithm.py
  mslice/workspace/histogram_workspace.py
Labels: bug

#498 Added override to avoid load overwrite dialog
  mslice/cli/_mslice_commands.py
  mslice/presenters/data_loader_presenter.py
  mslice/tests/command_line_test.py
Labels: bug

#506 Fixed save dialog unhandled exception
  mslice/models/workspacemanager/file_io.py
  mslice/plotting/plot_window/plot_figure_manager.py
Labels: High priority, bug

#507 Plotting ads saved cuts bugfix
  mslice/util/mantid/algorithm_wrapper.py
  mslice/workspace/histogram_workspace.py
Labels: High priority, bug

#509 Wrap set_waterfall to force a call in the qapp thread
  mslice/cli/__init__.py
  mslice/plotting/plot_window/plot_figure_manager.py
  mslice/util/qt/qapp.py
Labels: High priority, bug
