Repository mantidproject/mslice, pull requests merged in 2021-04, with the labels that each got.

#588 549 delete curve feature
  .github/workflows/unittest.yml
  mslice/plotting/plot_window/cut_plot.py
  mslice/plotting/plot_window/plot_options.py
  mslice/presenters/plot_options_presenter.py
  mslice/tests/plot_options_presenter_test.py
Labels: enhancement, review wanted

#583 Added exception handling for different input values for GDOS to prevent MSlice crashes.
  mslice/models/slice/slice_functions.py
  mslice/models/units.py
  mslice/plotting/plot_window/slice_plot.py
Labels: bug, review wanted

#587 555 add workspace wrapper
  mslice/cli/_mslice_commands.py
  mslice/tests/command_line_test.py
Labels: enhancement, review wanted

#565 Implement floating/ontop window behaviour for mslice
  mslice/app/__init__.py
  mslice/app/mainwindow.py
Labels: review wanted

#589 Update mslicedevel.bat
  mslicedevel.bat
Labels: maintenance, review wanted
