Repository mantidproject/mslice, pull requests merged in 2022-06, with the labels that each got.

#774 Prevent strings in options for plot min and max axes values
  mslice/plotting/plot_window/plot_options.py
  mslice/plotting/plot_window/quick_options.py
Labels: bug

#760 Prevent error when loading OSIRIS data
  mslice/presenters/data_loader_presenter.py
  mslice/tests/workspace_algorithms_test.py
Labels: bug

#794 Fix bug that causes continual calls to "toggle_waterfall"
  mslice/plotting/plot_window/cut_plot.py
  mslice/plotting/plot_window/plot_window.py
Labels: bug, High priority

#796 Fix bragg peak qops to work with new colour mapping and line width
  mslice/models/colors.py
  mslice/plotting/plot_window/cut_plot.py
Labels: bug

#799 Fix error when closing interactive plot
  mslice/plotting/plot_window/slice_plot.py
  mslice/presenters/slice_widget_presenter.py
Labels: bug

#800 Added unit tests for some mslice.models
  .coveragerc
  mslice/tests/colors_test.py
  mslice/tests/projection_calculator_test.py
  mslice/tests/rebose_algorithm_test.py
  mslice/tests/units_test.py
  mslice/tests/workspace_algorithms_test.py
  mslice/tests/workspace_provider_test.py
  setup.cfg
Labels: maintenance

#802 Added information about MSlice conda packages
  README.md
  docs/source/quickstart.rst
Labels: maintenance, documentation
