Repository mantidproject/mslice, pull requests merged in 2023-02, with the labels that each got.

#866 Check 'Degrees' and '2Theta' for x dimension
  mslice/models/cut/cut.py
  mslice/models/labels.py
Labels: bug, High priority

#865 864 fix intensity change crash
  mslice/models/intensity_correction_algs.py
  mslice/tests/intensity_correction_algs_test.py
Labels: bug

#840 Update MSlice start script and documentation
  README.md
  docs/source/quickstart.rst
  mslice-developer.yml
  mslicedevel.bat
  mslicedevel.sh
  scripts/mslice
  scripts/mslice.bat
  scripts/start_mslice.bat
Labels: maintenance, documentation

#874 Fix IndexError caused by saving a slice as a matlab file
  mslice/models/workspacemanager/file_io.py
  mslice/models/workspacemanager/workspace_algorithms.py
Labels: bug

#870 Moved flake8 step before step with Mantid installation
  .github/workflows/unit_tests.yml
  .github/workflows/unit_tests_nightly.yml
Labels: maintenance
