Repository mantidproject/mslice, pull requests merged in 2023-01, with the labels that each got.

#846 MPL 3.6.2 updates
  mslice/plotting/plot_window/plot_window.py
  mslice/plotting/pyplot.py
  mslice/presenters/quick_options_presenter.py
  mslice/scripting/helperfunctions.py
  mslice/tests/quick_options_test.py
  tools/boilerplate.py
Labels: maintenance

#848 Allow custom hex color when opening plot options
  mslice/models/colors.py
  mslice/tests/colors_test.py
Labels: bug

#852 Fix for segmentation fault in unit test workflows
  .github/workflows/deploy_conda.yml
  .github/workflows/deploy_conda_nightly.yml
  .github/workflows/online_doc_update.yml
  .github/workflows/unit_tests.yml
  .github/workflows/unit_tests_nighly.yml
  mslice/tests/plotselector_view_test.py
  setup.py
Labels: bug, High priority
